apiVersion: apps/v1
kind: Deployment
metadata:
<<<<<<< HEAD
  name: api-tareas
  namespace: tareas-namespace
=======
  name: api-oauth
  namespace: tasks-namespace
>>>>>>> main

spec:
  selector:
    matchLabels:
<<<<<<< HEAD
      app: api-tareas
=======
      app: api-oauth
>>>>>>> main
  replicas: 1
  template:
    metadata:
      labels:
<<<<<<< HEAD
        app: api-tareas
    spec:
      
      containers:
        - name: api-tareas
=======
        app: api-oauth
    spec:
      
      containers:
        - name: api-oauth
>>>>>>> main
          image: loliconario69/laravel:v3
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
<<<<<<< HEAD
                name: configuracion-de-tarea
          volumeMounts:
            - mountPath: /app
              name: proyecto
      volumes:
        - name: proyecto
          hostPath: 
            path: /root/Proyecto-Prog-posix
=======
                name: configuracion-de-oauth
          volumeMounts:
            - mountPath: /app
              name: project
      volumes:
        - name: project
          hostPath: 
            path: /root/api-auth
>>>>>>> main
            type: Directory

---

apiVersion: apps/v1
kind: Deployment
metadata:
<<<<<<< HEAD
  name: mysql-tareas
  namespace: tareas-namespace
spec:
  selector:
    matchLabels:
      app: mysql-tareas
=======
  name: mysql-oauth
  namespace: tasks-namespace
spec:
  selector:
    matchLabels:
      app: mysql-oauth
>>>>>>> main
  replicas: 1
  template:
    metadata:
      labels:
<<<<<<< HEAD
        app: mysql-tareas
    spec:
      containers:
        - name: mysql-tareas
=======
        app: mysql-oauth
    spec:
      containers:
        - name: mysql-oauth
>>>>>>> main
          image: mysql:8
          ports:
            - containerPort: 3306
              name: web
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
<<<<<<< HEAD
              value: tareas
=======
              value: usersdb
>>>>>>> main
