apiVersion: v1
kind: Service
metadata:
<<<<<<< HEAD
  name: api-tareas
  namespace: tareas-namespace
spec:
  type: NodePort
  selector:
    app: api-tareas
=======
  name: api-oauth
  namespace: tasks-namespace
spec:
  type: NodePort
  selector:
    app: api-oauth
>>>>>>> main
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
<<<<<<< HEAD
      nodePort: 30301
=======
      nodePort: 30302
>>>>>>> main
---

apiVersion: v1
kind: Service
metadata:
<<<<<<< HEAD
  name: mysql-tareas
  namespace: tareas-namespace
spec:
  type: NodePort
  selector:
    app: mysql-tareas
=======
  name: mysql-oauth
  namespace: tasks-namespace
spec:
  type: NodePort
  selector:
    app: mysql-oauth
>>>>>>> main
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
<<<<<<< HEAD
      nodePort: 30201
=======
      nodePort: 30202
>>>>>>> main
